### ISSUE TITLE
Just some questions

### ISSUE THREAD

**Issue by cnlohr** [Janky-Jingle-Crew/NorthPoleCircuit#1]
Actually I've got a few questions and comments.

1. I downloaded your kicad files, would be cool for you to include a PCB shot in the readme.
2. The readme itself at the beginning is a little corrupty, may want to fix it.  Github no longer allows embedding of youtube embeds that way, you have to now do it this way: 
```
[![IMAGE ALT TEXT HERE](https://img.youtube.com/vi/YOUTUBE_VIDEO_ID_HERE/0.jpg)](https://www.youtube.com/watch?v=YOUTUBE_VIDEO_ID_HERE)
```
I.e.
```
[![North Pole Circuit - 2024 Christmas Card](https://img.youtube.com/vi/rN7HYXmgxzk/0.jpg)](https://www.youtube.com/v/rN7HYXmgxzk)
```

The questions:

1. I have never done anything with Lorenz forces, but, wouldn't it be better if there was not copper fill under the track (on B.Cu and In2)?
2. I am having a hard time following the mechanism for how your track is designed, especially the top layer, it feels really confusing that it would wrap around and backtrack on the outside instead of go around twice? 
3. Would you be willing to draw up your waveform generation? Or even have a capture of G1_OUT/G2_OUT, B1_OUT/B2_OUT, A1_OUT, A2_OUT. 
4. I notice you have UART on your programming header.  Did you find anything wrong with the printf-over-swio, in 003fun?

**Comment by Muoshy** [comment]
Hi cnlohr,
Thanks for the feedback and also the great resources in ch32v003fun, been an absolute pleasure working with it.

1. Good suggestion, will definitely add one.

2. The readme is used to render [this page](https://janky-jingle-crew.com/NorthPoleCircuit) at the same time. 
Because of markdown/HTML conflicts, it's looking a bit janky right now. We will probably separate them later on.

Great questions. had to think a bit for these. I will do my best to answer them.

1. The copper fills are mainly there for lazy power and GND routing. Good question, I also think it would be better but not sure how.... On top of my head I can think of eddy currents and field distribution.

**Eddy currents:**
Eddy currents will definitely be induced in the copper fills. These are proportional to the rate of change in the B-field (dB/dt).
I can see three sources of these.
* The current ripple on the sinusoidal PWM will generate a changing B-field. High frequency (100 kHz) but low amplitude due to extra inductor and high PWM frequency. Low dB/dt / eddy losses here.
* The phase currents will also generate a changing B-field. Higher amplitude but low frequency (~100 Hz range). Should also be low dB/dt / eddy losses.
* The magnet movement. Definitely has the highest field strength but unsure about the dB/dt for this one. Pretty sure we also get some Lenz Law action here working against the magnet movement a bit. Removing the copper fill would definitely help here....

**Field distribution:**
Initially, I assumed the copper would act as a "shield," concentrating/squeezing the field near the fill. However, I later realized that copper is non-ferrous, and since we're dealing with B-fields, it shouldn't influence the B-field distribution and the resulting forces. Will affect E-fields though!

Open to discussion regarding these points. Could definitely be a few hiccups in my thought process on these questions.

2. The guard rail (top layer) needs to wrap around so we get the current on the outside and inside rails flowing in opposite directions. Otherwise, one rail will generate an inwards force and the other one will generate an "outside" force. Here's a really bad sketch (might be wrong force direction but principle still holds). Hopefully it makes sense. I will try to add a sketch of the A/B phase propulsion to the readme as well.
![image](https://github.com/user-attachments/assets/0ef20a41-f2f8-4ffe-ad1d-87c614eea868)

3. Definitely! I will scope out some signals and add it to the readme.
It's just PWM with the duty cycle following a sine wave to control the phase currents. A and B are then phase shifted 90deg. So when A is max duty cycle, B will be 0. The guard rail just has a fixed duty cycle to generate a constant inwards force. 

4. I never had the time to test the printf-over-swio functionality but saving 2 pins is definitely helpful.
Does it work with the WCH-LinkE and would you mind pointing me to the example?

**Comment by cnlohr** [comment]
1/2. I never would have thought to use README to feed a website.  That's a pretty good idea.  Gosh I wish github would loosen up some of their readme restrictions.  For instance, I really wish you could direct-link off-github im
ages, etc. 

1. I still struggle to think through the difference between E and B fields, and separating them in my head. Thank you so much for the clarification.
2. About the top rail, it just feels weird to have an inversion at the bottom. I just opened up gimp and started drawing what I meant, but then I realized, I couldn't draw it.  Like even though what you have feels intuitively wrong to me, I think it's right.  That said - would it be better to do something like this?  Or is this what you did?
![image](https://github.com/user-attachments/assets/c256c2a5-d3bb-4c41-8a48-428e6f355223)

If I understand right, this is what you are doing? 
![image](https://github.com/user-attachments/assets/39c9b807-f07d-4a6e-b6d6-cdba7c27e935)


3. I would really appreciate it.  I don't know I'll ever do a project that uses this but, I would love to more deeply understand this in case I can find an application.
4. `debugprintfdemo` -- And it's not just saving pins, it's more for the convenience.

**Comment by Muoshy** [comment]
1. No worries, I stumbled into the same E/B field pitfall when I first tried to answer that question.

2. I understand your struggles, we also had ponder a lot when routing the guard rails for the first time. 

I think your version could work. In your case, you are paralleling the inner & outer loops and effectively halving the guard rail resistance. This is great and would lower power consumption even more. However, this also means the inner and outer loops will have different currents. This might lead to uneven guard rail strength on the inner/outer loops. I will have to test this sometime.

I did some quick calculations and in our case this comes out to roughly 30% more current in the inner loop. However, when you factor in driver resistance (0.3/2 ohms as guard driver is paralleled), the difference shrinks to only 15%. With some other parasitics included or worse drivers, I believe your suggestion might be better. 

Tuning the trace width of the guard rails is also one way to solve this. In that case your suggestion would be the optimal one and reduce power consumption by quite a lot. I will have to try this if I ever revisit this type of project.

Small detail: It might be good to overlap the guard rail crossings on top of each other like this. This should cancel out the forces when the magnet is right on top of the guard rail crossings. Seems to work well in our case but we haven't tried without the overlap.
![image](https://github.com/user-attachments/assets/182ecb28-aa2f-485c-acb0-b913d7dd44bc)

3. Absolutely! I will ping the thread/issue once it's added to the readme.

4. Great, I will take a look at it for further CH32 projects.

**Comment by Muoshy** [comment]
Here is a diagram of the A/B PWM waveforms along with the current directions for three "steps", it should also be in the readme now. Hopefully it makes sense. Let me know if I can close the issue or if you have additional questions. 

![Image](https://raw.githubusercontent.com/Janky-Jingle-Crew/NorthPoleCircuit/refs/heads/main/Media/A_B_diagram.png)

**Comment by dazhbog** [comment]
Can you please put the YouTube video at the first line of the readme/repo description? Way cooler to see it in action first! Also on your website its not clear that the first image is an actual link to YouTube. 

Amazing project!

**Comment by cnlohr** [comment]
Oh gosh thank you for all this clarification!  I could recommend you add this to your readme, it would be really helpful if this info was indexed on the internet better.

**Comment by cnlohr** [comment]
Aww! It looks great! Thanks for adding it. Happy holidays!
